apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: staging
spec:
  entryPoints:
    - vpn-web
  routes:
    - match: Host(`traefik.staging.internal`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
