apiVersion: apps/v1
kind: Deployment
metadata:
  name: catch-all-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: catch-all
  template:
    metadata:
      labels:
        app: catch-all
    spec:
      initContainers:
        - name: clone-repo
          image: alpine/git
          command:
            - /bin/sh
            - -c
            - "git clone https://github.com/InkedCat/AspireServer /aspire"
            - "cp -r /aspire/catch-all/errors /data"
          volumeMounts:
            - name: html-volume
              mountPath: /data
      containers:
        - name: catch-all
          image: catch-all:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: config-volume
          configMap:
            name: catch-all-config
        - name: html-volume
          emptyDir: {}
