kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-kube-system
      app.kubernetes.io/name: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: traefik-kube-system
        app.kubernetes.io/name: traefik
    spec:
      serviceAccountName: traefik
      containers:
        - name: traefik
          image: traefik:v3.3
          args:
            - --global.checkNewVersion=true
            - --global.sendAnonymousUsage=false

            - --api.dashboard=true
            - --ping=true
            - --providers.kubernetesCRD

            - --entrypoints.web.address=:8000
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.web.http.redirections.entryPoint.permanent=true

            - --entrypoints.websecure.address=:8443
            - --entrypoints.websecure.http.tls=true

            - --entrypoints.internal.address=:9000

            - --log.level=DEBUG
            - --accesslog=true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 8443
            - name: vpn-web
              containerPort: 8081
