kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.3
          args:
            - --global.checkNewVersion=true
            - --global.sendAnonymousUsage=false

            - --api.dashboard=true
            - --ping=true
            - --providers.kubernetesCRD

            - --entrypoints.web.address=:8080
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.web.http.redirections.entryPoint.permanent=true

            - --entrypoints.websecure.address=:8443
            - --entrypoints.websecure.http.tls=true

            - --entrypoints.vpn-web.address=:8081
            - --entrypoints.vpn-web.http.middlewares=vpn-only

            - --log.level=DEBUG
            - --accesslog=true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - name: web
              containerPort: 8080
            - name: websecure
              containerPort: 8443
            - name: vpn-web
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /ping
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
