kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.3
          args:
            - --global.checkNewVersion=true
            - --global.sendAnonymousUsage=false

            - --api.dashboard=true
            - --providers.kubernetesCRD

            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.web.http.redirections.entryPoint.permanent=true

            - --entrypoints.websecure.address=:443

            - --entrypoints.vpn-web.address=:81
            - --entrypoints.vpn-web.http.middlewares=vpn-only
            - --log.level=DEBUG
            - --accesslog=true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: vpn-web
              containerPort: 81
