kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-kube-system

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: traefik-kube-system
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik-kube-system
    spec:
      serviceAccountName: traefik
      priorityClassName: system-cluster-critical
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      containers:
        - name: traefik
          image: traefik:v3.3
          imagePullPolicy: Always
          args:
            - --global.checkNewVersion=true
            - --global.sendAnonymousUsage=false

            - --api.dashboard=true
            - --ping=true
            - --providers.kubernetesCRD
            - --providers.kubernetesingress

            - --entrypoints.web.address=:8000
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.web.http.redirections.entryPoint.permanent=true

            - --entrypoints.websecure.address=:8443
            - --entrypoints.websecure.http.tls=true

            - --entrypoints.internal.address=:9000

            - --log.level=DEBUG
            - --accesslog=true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 8443
            - name: internal
              containerPort: 9000
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
