apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      nodePort: 8080
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-websecure-service

spec:
  ports:
    - name: websecure
      protocol: TCP
      port: 443
      nodePort: 8443
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-vpn-web-service

spec:
  ports:
    - name: vpn-web
      protocol: TCP
      port: 81
      nodePort: 8081
  selector:
    app: traefik
