apiVersion: v1
kind: Service
metadata:
  name: traefik

status:
  loadBalancer:
    ingress:
      - ip: ""
        ipMode: VIP

spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
    - name: websecure
      protocol: TCP
      port: 443
      targetPort: websecure
    - name: vpn-web
      protocol: TCP
      port: 81
      targetPort: vpn-web
