---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  type: NodePort
  ports:
    - targetPort: web
      port: 80
      nodePort: 30080
  selector:
    app: traefik
---
apiVersion: v1
kind: NodePort
metadata:
  name: traefik-websecure-service

spec:
  type: LoadBalancer
  ports:
    - targetPort: websecure
      port: 443
      nodePort: 30443
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-vpn-web-service

spec:
  type: NodePort
  ports:
    - targetPort: vpn-web
      port: 81
      nodePort: 30081
  selector:
    app: traefik
