apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: web
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-websecure-service

spec:
  ports:
    - name: websecure
      protocol: TCP
      port: 8443
      targetPort: websecure
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-vpn-web-service

spec:
  ports:
    - name: vpn-web
      protocol: TCP
      port: 8081
      targetPort: vpn-web
  selector:
    app: traefik
