apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-kube-system

spec:
  type: NodePort
  ipFamilyPolicy: PreferDualStack
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-kube-system
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: web
      nodePort: 30080
    - name: websecure
      protocol: TCP
      port: 8443
      targetPort: websecure
      nodePort: 30443
    - name: vpn-web
      protocol: TCP
      port: 8081
      targetPort: vpn-web
      nodePort: 30081
