apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: web
      nodePort: 30080
    - name: websecure
      protocol: TCP
      port: 8443
      targetPort: websecure
      nodePort: 30443
    - name: vpn-web
      protocol: TCP
      port: 8081
      targetPort: vpn-web
      nodePort: 30081
