apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
dryRun: false
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  taints:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
localAPIEndpoint:
  advertiseAddress: 172.31.1.69
  bindPort: 6443

---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
etcd: {}
networking:
  serviceSubnet: 10.96.0.0/16,2001:db8:42:1::/112
  podSubnet: 10.244.0.0/16,2001:db8:42:0::/56
  dnsDomain: cluster.local
kubernetesVersion: 1.32.0
apiServer: {}
controllerManager: {}
scheduler: {}
dns: {}
proxy: {}
certificatesDir: /etc/kubernetes/pki
imageRepository: registry.k8s.io
clusterName: dedi-fedora-cluster
encryptionAlgorithm: RSA-4096
caCertificateValidityPeriod: 87600h0m0s
certificateValidityPeriod: 8760h0m0s
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
resolvConf: /etc/resolv-kube.conf
failSwapOn: false
featureGates:
  NodeSwap: true
memorySwap:
  swapBehavior: LimitedSwap
