apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
dryRun: false
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  taints: []
  imagePullPolicy: IfNotPresent
  imagePullSerial: true

---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
networking:
  serviceSubnet: 10.96.0.0/16,2001:db8:42:1::/112
  podSubnet: 10.244.0.0/16,2001:db8:42:0::/56
  dnsDomain: cluster.local
kubernetesVersion: 1.32.1
certificatesDir: /etc/kubernetes/pki
imageRepository: registry.k8s.io
clusterName: dedi-fedora-cluster
encryptionAlgorithm: RSA-4096
caCertificateValidityPeriod: 87600h0m0s
certificateValidityPeriod: 8760h0m0s
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
resolvConf: /etc/resolv-kube.conf
featureGates:
  NodeSwap: true
memorySwap:
  swapBehavior: LimitedSwap
