apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
dryRun: false
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
  kubeletExtraArgs:
    - name: "node-ip"
      value: "${PRIMARY_IPV4},${PRIMARY_IPV6}"

---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
networking:
  serviceSubnet: 10.96.0.0/16,2001:db8:42:1::/112
  podSubnet: 10.244.0.0/16,2001:db8:42:0::/56
  dnsDomain: cluster.local
kubernetesVersion: ${KUBERNETES_VERSION}
certificatesDir: /etc/kubernetes/pki
imageRepository: registry.k8s.io
clusterName: dedi-fedora-cluster
encryptionAlgorithm: RSA-4096
caCertificateValidityPeriod: 87600h0m0s
certificateValidityPeriod: 8760h0m0s
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
resolvConf: /etc/resolv-kube.conf
memorySwap:
  swapBehavior: LimitedSwap
